### ISSUE TITLE
Unlock and Lock

### ISSUE THREAD

**Issue by muaxiaohei** [hepingood/w25qxx#10]
### Please ask your question

Hello, Thank you for your works in generic drivers.
I have a question. Why don't we add unlock and lock operation in drivers to ensure mutually exclusive operation？🤔

**Comment by hepingood** [comment]
Hello, thank you very much for using the LibDriver driver. The LibDriver driver design follows the bottom-up design principle. As a component of the BSP, the driver is specially designed to operate various hardware. As one of the system functions, mutex is located at the upper layer of BSP. When hardware functions need to be called above the system layer, the system layer mutex function should be used to protect various operations of the hardware and ensure that the hardware driver only does one thing at the same time.
There are currently many drivers on the market that lock and unlock the driver through a flag at the driver layer to simulate the operation of a mutex. This operation is problematic. When multiple requests arrive, the mutex should be redundant. The request is suspended and executed sequentially according to the specified request rules. Simulating the mutex operation through a flag will only return an error when encountering a locked state. Obviously this is a wrong way to handle mutexes. Many MCUs are executed in unsystematic order. Adding useless simulated mutex operations will only increase the probability of driver locking BUG.
When the driver is used for system-less sequential execution such as MCU, the driver can be used directly. When the driver runs on an OS or RTOS system, a mutex at a higher system layer should be used to protect the driver operation. Many open source middleware and Linux, etc. The BSP of the system requires this.

您好，非常感谢您使用LibDriver驱动，LibDriver驱动设计遵循从下到上的设计原则，驱动作为BSP组成部分，它被专门设计用来操作各种硬件。互斥量作为系统功能之一处于BSP的上层，当系统层以上需要调用硬件功能时，应该利用系统层互斥量功能保护硬件的各类操作，确保同一时间硬件驱动只做一件事情。
当前市场上有很多驱动在驱动层通过一个标志位对驱动进行锁住和解锁操作，模拟互斥量的操作，这个操作是有问题的，当多个请求到来的时候，互斥量应该将多余的请求挂起，按照指定请求规则依次执行，而通过标志位模拟互斥量操作遇到锁住状态只会返回错误，显然这是一种错误的互斥量处理方式。很多MCU都是无系统顺序执行的，增加无用的模拟互斥量操作，只会增加驱动被锁住BUG的发生概率。
当驱动用于MCU等无系统顺序执行时，可以直接使用驱动，当驱动运行在OS或者RTOS等系统时，应该利用更高系统层的互斥量保护驱动操作，很多开源的中间件及Linux等系统的BSP都是这样要求的。

**Comment by muaxiaohei** [comment]
Thanks, your answer are very helpful!!!😘I am very happy to learn new knowledge~
