### ISSUE TITLE
where can i find spi_qspi_write_read function in source code？

### ISSUE THREAD

**Issue by zhajio1988** [hepingood/w25qxx#3]

**Comment by hepingood** [comment]
Hello, we provide the templates of w25qxx interface in /interface. You can implement these functions according to your platform. In /project, we have implemented raspberrypi4b (SPI), stm32f407 (SPI), stm32f767 (spi&&qsi). These projects can help implement your interface.

你好，我们在/interface目录下提供了W25QXX接口的模板，您可以根据您的平台实现这些函数。在/project目录下，我们实现了raspberrypi4b(SPI),stm32f407(SPI),stm32f767(SPI&&QSI)，这些工程可以帮助实现您的接口。
